store_folder_path = "storage/"
lan_interface_name = "eth0"
usv_name = "ups"
usv_description = "Victron Cerbo GX"
usv_contact = "kipik@kipik.com"
usv_location = "ZA-BB"
inverter_shutdown_soc = 10
auth_required = false
battery_wh = 5000

[[users]]
username = "test"
password = "test"

[[shutdown_policies]]
name = "Shutdown servers"
shutdown_soc = 20
restart_soc = 25
binding_nut_ip = "192.168.150.21"
restart_wol = { mac = "00:1e:67:d6:61:f6", destination = "192.168.154.12:4000" }
restart_http_request = { url = "https://192.168.156.80/tfwopaque/pdumodel.Outlet:2.1.5/outlet.8", basic_auth = "admin:admin", post_data = "{\"jsonrpc\":\"2.0\",\"method\":\"cyclePowerState\",\"params\":null,\"id\":0}" }
